PROMPT="""

Please analyze   text sample : {input_text} for authenticity analysis.
You will analyze the provided text and determine whether it was generated by AI or written by a human
The analyze will include  linguistic patterns, stylistic markers, and semantic coherence to predict whether the text was generated by a human writer or an artificial intelligence language model.

The analysis will include:

To facilitate this evaluation, you will employ the following detection criteria:
   - Critically measure the perplexity and burstiness levels in the specific text. 
   - Analyze the basic token predictability in relation to the established tendencies of AI generation. 
   - Recognize odd patters of repetitions, overuse of politeness, and shallow arguments. 
   - Distinguish the stylistic features typical of various AI models (specify old and new model).

The output requirements are as follows: 
  - You should identify the text is either AI Generated or Human Generated.  
  - Or estimate a conviction score as a percentage for your claim.  
  - What are the guidelines that impacted your verdict?  
  - Provide some statistics as well including the perplexity, entropy and token frequency analysis.

The Output format will be in the following format:

Analysis Report:  
- Decision: [AI-Generated / Human-Generated]  
- Confidence Score: [e.g., 96%]  
- Statistical Breakdown:  
  - Perplexity: [value]  
  - Burstiness: [value]  
  - Token Predictability: [value]  
  - Entropy: [value]  
- Key Observations:  
  - [e.g., Unnatural phrasing detected...]  
  - [e.g., Token repetition consistent with AI-generated text...]  


Always cross-verify the analysis using different detection methodologies. 
Provide a disclaimer if uncertainty arises due to text length or ambiguity.  



"""